### ISSUE TITLE
Starting development server ERROR: Migration...

### ISSUE THREAD

**Issue by aprilalayon** [vapid/vapid#100]
1) When starting the server there is an error. 
`==> Starting the development server... 
ERROR: Migration 20180513195752-create-users.js (or wrapper) didn't return a promise`

1. Install npm vapid-cli package
2. Create a new project folder
3. vapid start . doesn't output anything and shows the error
`==> Starting the development server... 
ERROR: Migration 20180513195752-create-users.js (or wrapper) didn't return a promise`

Environment
 - MacOS: 10.14.1
 - Node Version v10.13.0
 - Vapid Version vapid-cli@0.3.2

I've tried to look for this issue but did not see any bug or answers in the forum.

**Comment by ktquez** [comment]
Me too

**Comment by ibdf** [comment]
Same here. I followed the exact steps on the vapid home page.

**Comment by srobbin** [comment]
Thanks for letting me know. I'll look into this today.

**Comment by srobbin** [comment]
Just released v0.3.3, which _should_ fix this problem. 🤞 

To update: `npm install -g vapid-cli`

Let me know if that does/doesn't work.

**Comment by ibdf** [comment]
Can confirm that's working after the fix.
