### ISSUE TITLE
Adding sourcemaps for development

### ISSUE THREAD

**Issue by Hadr619** [vapid/vapid#104]
**Is your feature request related to a problem? Please describe.**
During development developers may choose to see which scss partial styles are located with in a browser's developer tools.

**Describe the solution you'd like**
Adding a feature to include sourcemapping in development mode would speed development 

**Describe alternatives you've considered**
With the inclusion of dart sass sourcemapping should be available

**Comment by srobbin** [comment]
@Hadr619 Good idea. I just submitted PR #105 with source maps turned on in development. Let me know if you're able to review it before I merge.

**Comment by Hadr619** [comment]
@srobbin This will be awesome, thank you

**Comment by srobbin** [comment]
@Hadr619 Just released v0.3.5 which includes this PR. Thanks again for submitting this.
