### ISSUE TITLE
Items sort not correct on deploy

### ISSUE THREAD

**Issue by Jack89ita** [vapid/vapid#107]
When i deploy my new website on vapid hosting, the sortable items in sections don't reflect the development order; so every time i do a new deploy, i have to reorder items with drag and drop every time.
Any tips?
Thank you very much!

EDIT: it seems that reordering items it's not working properly, when i drag and drop items, the one that i drag is ordered correctly, but the others are always jumping in a different order...

**Comment by srobbin** [comment]
@Jack89ita This should be fixed in the most recent release, v0.5.1.

As a reminder, the NPM package name has changes from `vapid-cli` to `@vapid/cli`. To update:

```
npm uninstall -g vapid-cli
npm install -g @vapid/cli
```
