### ISSUE TITLE
Error when updating package

### ISSUE THREAD

**Issue by Jack89ita** [vapid/vapid#112]
Hello, i was trying to update to the last release: uninstalling is ok but when i run
```npm install -g @vapid/cli```
i get the following error:
![untitled-2](https://user-images.githubusercontent.com/15101779/50550138-8ccfb500-0c6a-11e9-962f-b05a5fedbccb.jpg)

Any clue?
Thanks!

**Comment by srobbin** [comment]
Looks like it's having trouble finding Python on your system. Do you know if you already have it installed? If so, the solution might be as easy as putting the location in your PATH. If not, here's the downloads page: https://www.python.org/downloads/windows/

**Comment by Jack89ita** [comment]
Hey @srobbin, following your idea i've installed python (3.7.2), now when i'm launching the install command this is the error:
![untitled-1](https://user-images.githubusercontent.com/15101779/50573318-14840380-0dd2-11e9-91e1-1d430e2e5b9a.jpg)
Maybe i need to install a different version?

**Comment by srobbin** [comment]
Yah, it looks like the bcrypt modules depends on Python 2, and you've got Python 3 installed. Try [uninstalling Python 3](https://www.wikihow.com/Uninstall-Python), and then [installing Python 2.7](https://www.python.org/downloads/release/python-2715/).

**Comment by Jack89ita** [comment]
Hi @srobbin, i installed python 2.7 but i still can't update or install @vapid/cli.
Why should i need python by the way?
Should i rollback version of vapid? because now i can't even start the development in my local machine..
Thanks

**Comment by srobbin** [comment]
Are you seeing any error messages? If so, please post them.

Re: Python, bcrypt is requiring it, because it can't find a prebuilt binary for the version of Node you're using. So, it uses Python to compile bcrypt from the source.

**Comment by Jack89ita** [comment]
Yes there are some errors, here the screenshot:
![untitled-1](https://user-images.githubusercontent.com/15101779/50778791-1ac92280-129f-11e9-86a6-9a120797710b.png)

Ok let's move on forum thanks

**Comment by Jack89ita** [comment]
Solved: need to install the package using node v8.10.0 as described [here](https://forums.vapid.com/t/production-mode-and-bcrypt-issues-on-v-0-5-1/174)
Thanks
