### ISSUE TITLE
Time=true in a date field broken

### ISSUE THREAD

**Issue by ohnoimdead** [vapid/vapid#117]
**Describe the bug**

```{{testdate type=date time=true}}```
Results in a text field with the value "undefined" in the dashboard and no date/time UI.

**To Reproduce**
1. Create new vapid site
2. Modify index.html adding: ```{{#section testings}}{{testdate type=date time=true}}{{/section}}```
3. Navigate to dashboard
4. <img width="262" alt="image" src="https://user-images.githubusercontent.com/35269/53289197-5c505700-3793-11e9-866d-2f8526e0dbf4.png">

**Expected behavior**
Dashboard shows a datetime picker similar to a basic {{testdate type=date}} field with an additional time component.

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: OS X
 - Browser: Firefox, Safari (latest)
 - Node Version: v10.14.2
 - Vapid Version: Vapid 0.6.0

**Additional context**
The date field appears to validate as text. When the record is saved the site shows the text entered into the date field, including "undefined", if saved with changes.

**Comment by ohnoimdead** [comment]
FWIW it looks like vapid is emitting a <input type="datetime-local"> but setting the value to "undefined". Possibly due to format not being supplied?

**Comment by srobbin** [comment]
@ohnoimdead Good catch. Looks like it was missing a default value.

**Comment by srobbin** [comment]
Just published v0.7.0 w/ the fix. Thanks again for reporting this.
