### ISSUE TITLE
Deployment to Glitch 

### ISSUE THREAD

**Issue by PHironaka** [vapid/vapid#120]
I tried to deploy a Vapid site to Glitch, and nothing is showing up.

Any steps we need to make other than syncing our github repo?

**Comment by PHironaka** [comment]
Just checked the logs on Glitch and got the following error when I tried using vapid start .: 

`/rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/build/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/build/Debug/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/build/Release/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/out/Debug/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/Debug/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/out/Release/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/Release/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/build/default/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/compiled/10.15.0/linux/x64/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/lib/binding/node-v64-linux-x64/sharp.node
    at bindings (/rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/lib/index.js:3:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dfw@ start: `vapid start .`
 → /rbd/pnpm-volume/7eeb2e09-4829-45cb-8e08-fdc381d72e61/node_modules/.registry.npmjs.org/sharp/0.21.3/node_modules/sharp/build/sharp.node
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dfw@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/10.15.0/_logs/2019-03-05T21_16_27_057Z-debug.log`


To confirm, I am able to get the site running on my local machine.

**Comment by srobbin** [comment]
@PHironaka I'm sorry to hear about the troubles on Glitch. It's been a while since I've run it on there, but I can take a look. In the meantime, would you mind posting this question to the [Vapid Forums](https://forums.vapid.com/)? That's a better venue for hosting/third-party questions. I'll jump in over there with a reply.

**Comment by PHironaka** [comment]
@srobbin i added this question to the forum - https://forums.vapid.com/t/issue-deploying-to-glitch/219?u=phironaka

I could use some help deploying this site, as I'm not too familiar with Vapid. I tried with Heroku earlier and it failed to load.
