### ISSUE TITLE
Feature Request: Soft wrap in markdown editor

### ISSUE THREAD

**Issue by ohnoimdead** [vapid/vapid#125]
Would be nice if the markdown editor soft-wrapped long paragraphs so the entire paragraph is visible without having to scroll horizontally. Might be a feature of ace, not sure.

Adding carriage returns results in <br>'s in the output html (which is the correct behavior for markdown) so that's not a workaround for this issue.

**Comment by srobbin** [comment]
@ohnoimdead Looks like it's [an easy option to add](https://github.com/vapid/vapid/pull/126/files#diff-0a391524434eff19b3a0c30131e28303R10). It'll go out in the next release. Thanks!
