### ISSUE TITLE
Use wss:// for sites serving https://

### ISSUE THREAD

**Issue by tonysusi** [vapid/vapid#129]
I've deployed my vapid site to ssl site. While in the dashboard editing a textarea, the console is rendering the following error:

`Mixed Content: The page at 'https://example.com/dashboard/records/1' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://example.com/livereload'. This request has been blocked; this endpoint must be available over WSS.`

Looking over the code, I think I found a fix. In assets/dashboard/javascripts/dashboard/websocket.js could you change

line 4:*
```javascript 
const ws = new WebSocket(`ws://${location.host}/livereload`);
```
 to 
```javascript 
const ws = (window.location.protocol == 'https:')? new WebSocket(`wss://${location.host}/livereload`) : new WebSocket(`ws://${location.host}/livereload`) ;
```

I'm happy to do the pull request to fix this.

**Comment by srobbin** [comment]
@tonysusi Thanks for submitting this and the associated PR.

I'm curious, why is Livereload running on your production server? Typically, that's only run in development mode, so it can monitor template changes and prompt you to rebuild the data model.

**Comment by tonysusi** [comment]
@srobbin Updating the .env with 'NODE_ENV=production',  sorted out my problem with ws:// and mixed content. Thanks for your help. No sure if you need to add that PR anymore.
