### ISSUE TITLE
Create new page from template

### ISSUE THREAD

**Issue by AndiLeni** [vapid/vapid#131]
Hello,

is it possible to add a new page from the admin panel and use f.e. an already existing page or a template?

Regards
Andi

**Comment by srobbin** [comment]
@AndiLeni Would you mind posting the question to the [Vapid forums](https://forums.vapid.com/)? We're trying to keep the GitHub issues focused on development issues, and use the forums as a place to answers questions about how to use Vapid? Thank you.
