### ISSUE TITLE
Can't save admin area

### ISSUE THREAD

**Issue by jordanmoon** [vapid/vapid#137]
**Describe the bug**
Unable to save any fields in the admin area

**To Reproduce**
1. Create a new site `vapid new vapidtest`
2. Click 'Login'
3. Create a login and sign in
4. Add a 'Background Image' + 'Greeting', then save
6. Error (screenshot below)

**Expected behavior**
Content to save

**Screenshots**
<img width="1425" alt="vapid-error" src="https://user-images.githubusercontent.com/19351135/56249383-788db780-60a3-11e9-999c-701ed6706d6a.png">

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: [OSX, High Sierra]
 - Browsers:  Chrome, Safari, Firefox
 - Node Version: 11.11.0
 - Vapid Version: 0.8.0

**Additional context**
Console log doesn't return any messages or errors. Neither does terminal. Sorry it's not much to go off!

**Comment by srobbin** [comment]
@jordanmoon Thanks for letting me know. I just published v0.8.1, which should fix the issue. Let me know if it does/doesn't work.

**Comment by jordanmoon** [comment]
@srobbin Thanks a bunch! Working perfectly now. 😄
