### ISSUE TITLE
Supporting 3rd party file system like Amazon S3

### ISSUE THREAD

**Issue by clawfire** [vapid/vapid#138]
Deploying Vapid on services like now.sh or Heroku leaves us with the issue of non-persistent file storage.
A file storage adapter system would be great, with like S3 adapter at first and let do the community work on other adapters?

**Comment by srobbin** [comment]
I [followed up on the forums about this](https://forums.vapid.com/t/hosting-on-heroku/244/2), but for future reference, here's the response:

> Re: storage, unfortunately, there isn’t anything implemented or in the works. IMO, this is one of the biggest pains using Heroku and other ephemeral hosts. I was hoping that one of them would eventually offer something akin to Amazon’s EFS, where the mounted file system is a virtual connection to S3. 

> That said, I’m open to pull requests or discussions about finding a solution. Or promoting a similar hosting service, if we can find one that’s no ephemeral, which maybe is DigitalOcean?
