### ISSUE TITLE
Feature Request: Multiple accounts

### ISSUE THREAD

**Issue by pschfr** [vapid/vapid#14]
This could make it easier to allow clients to only modify certain values in the future

**Comment by srobbin** [comment]
This should be easy enough to add, but one pre-condition is going to be adding a Forgot Password flow. I'm not sure what the best way to implement that is if we don't have email credentials.

**Comment by patrixr** [comment]
@srobbin An idea : could we perhaps use github accounts to log in. Implementation would be fairly simple and it would push all account/password management to github.

**Comment by srobbin** [comment]
@patrixr That's an interesting idea, however I think GitHub might alienate some users. For example, if I wanted to invite someone in my family, they'd have to go to GitHub to signup (after I gave them a tech support to explain what GitHub was), and then they go to the website... I think it would be preferable if Vapid had its own user management system. Maybe a centralized Vapid OAuth?

**Comment by pschfr** [comment]
Can we maybe not get this closed? :open_mouth:

**Comment by martinsoender** [comment]
@srobbin What about using something like Google Authenticator or adding personal questions to answer before signing in?

**Comment by srobbin** [comment]
@martinsoender I do like the idea of adding two-factor auth of some sort.

**Comment by w-biggs** [comment]
This is still needed...
