### ISSUE TITLE
Feature Request: Minified assets

### ISSUE THREAD

**Issue by pschfr** [vapid/vapid#15]
It would be cool if we could have minified versions of the CSS and JS, and perhaps the HTML too

**Comment by srobbin** [comment]
@pschfr In production, Webpack does minify JS files (those named with the .pack.js extension), but I don't think it strips out whitespace in CSS files. I imagine it's a setting we can add to [the Webpack config file](https://github.com/vapid/vapid/blob/master/lib/middleware/webpack/config.js). Do you have any experience with that, and could you suggest an edit?

**Comment by pschfr** [comment]
@srobbin according to this https://github.com/webpack-contrib/mini-css-extract-plugin#minimizing-for-production, it can be done with another plugin. I can investigate more later...

**Comment by Jack89ita** [comment]
Hi @pschfr, did you find a solution to this issue? I am waiting to be able to minify CSS too..
