### ISSUE TITLE
npm install -g @vapid/cli fails on linux

### ISSUE THREAD

**Issue by taciturasa** [vapid/vapid#152]
node - v12.10.0
OS - Anarchy Linux (Arch)
node & npm installed through manually installed nvm

When installing, it fails to install the specified version of sharp. Logs are attached.

[2019-09-24T15_49_59_330Z-debug.log](https://github.com/vapid/vapid/files/3648095/2019-09-24T15_49_59_330Z-debug.log)

**Comment by taciturasa** [comment]
Looking further, it seems this is because vapid relies on an outdated sharp, which does not work on Node 12.

**Comment by belmarca** [comment]
I have the same issue.

`Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux`

**Comment by belmarca** [comment]
Allowing greater versions of `sharp` seem to fix the issue.

**Comment by srobbin** [comment]
Fixed in #165
