### ISSUE TITLE
No variable for current url or base url

### ISSUE THREAD

**Issue by nsrosenqvist** [vapid/vapid#154]
From what I can gather (at least not in the docs) there is no way to access the current URL or site base URL. This prevents configuring opengraph tags and other meta correctly.

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: Ubuntu 18.04
 - Vapid Version: 0.8.6

**Comment by amiller-gh** [comment]
Mmm, this is a good feature addition. It will be especially needed if we get something like #158 or custom page slugs for collection records. How would you envision the API looking?

Side note – if pages and collection records get a more opinionated "settings" panel (mentioned at the end of #158 and in #8, we may want to add social media metadata config options on a per-page and per-post basis. This page settings proposal as not been written yet though and is probably tangential to a `{{_location}}` metadata addition. (FWIW, the Ghost Blog interface is great prior art for standard page settings)
<img width="352" alt="Screen Shot 2019-10-30 at 12 44 46 PM" src="https://user-images.githubusercontent.com/7856443/67893058-1cf0bc00-fb13-11e9-9448-dd4cc4460c43.png">

**Comment by nsrosenqvist** [comment]
Personally I'd simply want the request information to be made available in a global variable, containing full request url, base url, host and scheme, or a function that allows you to retrieve the absolute url for an asset.

**Comment by srobbin** [comment]
I agree. Maybe something like a `{{_request}}` tag, which exposes _some_ of the [Koa.js request variables](https://koajs.com/#request) (e.g., host, path, origin, query).

So you could end up doing something like:

```
<meta property="og:image" content="{{_request.origin}}/images/share.png">
```
