### ISSUE TITLE
Deploy to GCP App Engine error

### ISSUE THREAD

**Issue by BrujaVudu** [vapid/vapid#16]
Locally, it works perfect. But when I deploy it to GCP, I get this error:

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

In the CGP Console, I get this message:

> Error: Cannot find module '/srv/server.js'

Any ideas?

**Comment by srobbin** [comment]
@BrujaVudu I'm not familiar with deploying Node.js apps to App Engine, but it sounds like the service is launching the wrong startup script. What does your `package.json`file have as the start script? It should look something like this:

```
"scripts": {
  "start": "vapid start ."
},
```

**Comment by srobbin** [comment]
@BrujaVudu I'm not sure if you resolved this issue, but in either case, I'd like to move conversations about deployment issues over to the [Vapid forums](https://forums.vapid.com/). Please feel free to chime in over there, and update me on the progress of deploying to GCP.
