### ISSUE TITLE
Add an `else` tag to template logic

### ISSUE THREAD

**Issue by trst** [vapid/vapid#161]
**Is your feature request related to a problem? Please describe.**
It would be helpful to provide a fall back when using the `{{#if}}` tag. For example, I would like my blog post headers to link directly to source material if there is a link present, falling back to the section permalink when there is no link provided.

**Describe the solution you'd like**
Something along the lines of...

```html
<h2>
  <a href="{{#if source}}{{source}}{{#else}}{{_permalink}}{{/if}}">{{title}}</a>
</h2>
```

**Comment by employee451** [comment]
This is already possible with the use of the `{{unless}}` tag. It is used exactly like the if tag, only with the opposite logic. This is handy since you don't need an if tag if you want to do something when there aren't any records. This is possible with the unless tag. Hope this helps.
