### ISSUE TITLE
WSIWYG editor not allowing images

### ISSUE THREAD

**Issue by conjack27** [vapid/vapid#162]
**The issue**
Have added an HTML content type and want to add images. Have added "images=true", but it does not have the option to in the editor when in the Dashboard.

**Comment by srobbin** [comment]
@conjack27 What version of Vapid are you using?

```
vapid -v
```

**Comment by conjack27** [comment]
@srobbin vapid 0.9.2

**Comment by srobbin** [comment]
@conjack27 Strange. When you have a moment, can you please reply with:

1. Some more details about your environment: OS, Node version, browser
2. A screenshot of the WYSIWYG editor
3. A snippet of the template that creates the content type

**Comment by conjack27** [comment]
@srobbin sorry for late reply. This was solved by creating a new vapid project and then transferring the  html and css files over
