### ISSUE TITLE
Production server returns empty JSON object

### ISSUE THREAD

**Issue by employee451** [vapid/vapid#163]
**Describe the bug**
When the `NODE_ENV` environment variable is set to 'production', vapid sometimes returns an empty JSON object.

**To Reproduce**
1. Run `vapid new testsite`.
2. Rrun `cd testsite`.
2. Run `NODE_ENV=production npm start`.
3. Go to `localhost:3000` in the browser.

On first load, the server will often return an empty JSON object as the response, with a much longer than usual response time displayed in the terminal.

**Expected behavior**
Vapid should return the expected content instead of an empty JSON object.

**Your Environment**
 - OS: macOS Mojave 10.14.6
 - Browser: Google Chrome version 79.0.3945.88
 - Node Version: 12.14.0
 - Vapid Version: 0.9.2

**Comment by srobbin** [comment]
@employee451 Thanks for submitting this. I'm able to reproduce the bug too. I'll look into it.

**Comment by employee451** [comment]
No problem :)
I think it has something to do with the caching. 
The bug only occurs when the 'cache' value of the "Default options" object is true in /lib/runners/Vapid.js. Caching is enabled when this.isDev is false.

**Comment by employee451** [comment]
This bug should be fixed in PR #166.  
> When the cache isn't set, cache.set(cacheKey, await renderContent.call(this, ctx.path)) is run in 'lib/runners/VapidServer/index.js'. This, however, doesn't return anything for the ctx.body, so an empty JSON string is rendered.
In this PR, I fix the bug by checking whether the cache has been set (and setting it, if it hasn't been set) before assigning anything to ctx.body.

**Comment by srobbin** [comment]
Resolved in #166 and 2bab58c1bb21f7eb4928ef8fd7dc40bf3da26a31
