### ISSUE TITLE
More info on deployment

### ISSUE THREAD

**Issue by kosmaa** [vapid/vapid#17]
Maybe it is easy for some, but I have always problems with site deployment of node apps and I appreciate if it was more instructions on the process in DOCS, or more CLI options for it. To see how to do it.
I already tried  Vapid locally (and I love it) and I tried to deploy it on server (failed). So I would love to see more info on how to do it.

**Comment by srobbin** [comment]
@kosmaa Thanks for bringing this up. I just added a page to the project Wiki:

https://github.com/vapid/vapid/wiki/Self%E2%80%90hosting
