### ISSUE TITLE
Querying multiple records from same section does not work

### ISSUE THREAD

**Issue by JohJakob** [vapid/vapid#171]
In Vapid **0.9.0** to **0.9.4**, a bug reappears that was solved in version 0.8.4 (see issue #34 and  pull request #146).

In my case, I have got a navigation menu partial `_nav.html` that gets populated with records from multiple sections and looks like this:

```
<ul>
  {{#section foo multiple=true sortable=true}}
    <li>
      <a href="{{_permalink}}">{{title}}</a>
    </li>
  {{/section}}
</ul>
<ul>
  {{#section bar multiple=true sortable=true}}
    <li>
      <a href="{{_permalink}}">{{title}}</a>
    </li>
  {{/section}}
</ul>
```

On `index.html`, the whole menu displays all records from the sections, but on any detail page of these sections, the list with the records from the same section just renders the data of the currently open detail page.

The menu gets displayed correctly on Vapid **0.8.4** to **0.8.6**.

**Comment by srobbin** [comment]
@JohJakob Good catch, thank you. I just pushed v0.9.5 which reintroduces the fix.

**Comment by JohJakob** [comment]
@srobbin That was quick! Thanks a lot!

**Comment by walidvb** [comment]
Hi @srobbin are you planning on releasing it to the vapid hosting soon? Thanks!

**Comment by srobbin** [comment]
@walidvb Sorry about that, it should be up there now.
