### ISSUE TITLE
Ignore tag for using JS frameworks along with Vapid

### ISSUE THREAD

**Issue by afboteros** [vapid/vapid#172]
Hi,

There is a way on Vapid to specify that it should ignore a tag?, if you try for example to use Angular (or any other JS framework) along with Vapid, how do you split Angular brackets from Vapid's?

Thanks.

**Comment by srobbin** [comment]
Right now, Vapid doesn't have a way to change the brackets to something else, but thankfully Angular does:

```
angular.module('myApp', [], function($interpolateProvider) {
  $interpolateProvider.startSymbol('[{');
  $interpolateProvider.endSymbol('}]');
});
```

**Comment by afboteros** [comment]
I think that's AngularJS (v1) syntax, isn't it?, i will take a look for Angular 4> syntax for it.

**Comment by srobbin** [comment]
Ah, sorry, you're right. I haven't used Angular for a long time. I'm not sure what the current syntax is.
