### ISSUE TITLE
Bug: Reordering Sortable Posts not updating in Dashboard

### ISSUE THREAD

**Issue by JohJakob** [vapid/vapid#175]
When reordering sortable posts in the dashboard, the website updates accordingly, but the list in the dashboard will revert to the previous order when refreshed. However, the order on the rendered page will not revert.

**To Reproduce**
1. Open the dashboard
2. Go to a section with sortable posts
3. Reorder the posts
4. View the rendered page
5. Refresh the dashboard

**Expected behavior**
The order in the dashboard is the same as on the rendered page.

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: macOS Catalina 10.15.3
 - Browser: Safari 13.0.5
 - Node Version: 8.16.2
 - Vapid Version: 0.9.5

**Comment by jonasNobile** [comment]
Same problem. 

**My Environment is**

- OS: Ubuntu 18.04
- Browser: Safari 13.0.5, Firefox Developer Edition 75.0b5
- Node Version: 10.19.0
- Vapid Version: 0.9.5

**Comment by srobbin** [comment]
Thanks for letting me know. I'm a bit overloaded with personal things right now, so I may not be able to get to this for a bit. Would either of you be willing to help jump in and submit a pull request?

**Comment by JohJakob** [comment]
I’ve never worked on a Node.js project before, but I’ll try my best to find and fix the bug.
