### ISSUE TITLE
Feature request: Use Babel Loader in Webpack Config to Support React / Typescript

### ISSUE THREAD

**Issue by chwzr** [vapid/vapid#180]
I recently needed to integrate React Components in a Vapid Project to add interactivity.
Thus I needed to add the Babel Loader to Vapids Webpack Config.

"Babel is a tool that helps you write code in the latest version of JavaScript." - [babel](https://github.com/babel/babel)
Transpiling latest ES2015 JS Code to a more compatible version is mandatory in these days.

When [babel-loader](https://github.com/babel/babel-loader) is integrated in Webpack, one can simply add a .babel-rc to her Project folder to add more babel presets like @babel/preset-react for React or even adding Typescript support to the project with @babel/preset-typescript.

What do you think about adding this?
I can do a Fork/Merge if you are interested in adding this feature :) 

Cheers,
F

**Comment by JohJakob** [comment]
This sounds like a really nice feature. Vapid’s simplicity would still be maintained while one could extend its functionality if they want to.

**Comment by srobbin** [comment]
@chwzr I'd love this feature too, and would very much welcome a PR. Thank you.
