### ISSUE TITLE
Rendering a html page doesn't work anymore without extension suffix

### ISSUE THREAD

**Issue by bitterbit** [vapid/vapid#184]
**Describe the bug**
Let's say I have a vapid website with a full html page for my blog.
When previewing it one could use `/blog.html`  or `/blog` interchangeably. 
As of the master branch today, the latter doesn't work.

**To Reproduce**
1. Create a vapid site
2. Add an additional html page to the website
3. preview it and surf to `/page`, See that Template not found is printed in console.

**Comment by srobbin** [comment]
Resolved in #185
