### ISSUE TITLE
problem accessing multiple content using the {{_permalink}} tab

### ISSUE THREAD

**Issue by asitemade4u** [vapid/vapid#21]
I get a "Page not found" error.
Attached the record as a screenshot.
Copied the code from the doc example:

`
<ul>
  {{#section offices multiple=true}}
    <li>
      <h5><a href="{{_permalink}}">{{name}}</a></h5>
      {{city}}, {{state}}
    </li>
  {{/section}}
</ul>
`

![selection_001](https://user-images.githubusercontent.com/11460106/45885551-bd0eda00-bd84-11e8-8840-6a755e5dbf7b.png)

![selection_002](https://user-images.githubusercontent.com/11460106/45885630-ec254b80-bd84-11e8-894b-11a413805883.png)
What did I get wrong?

**Comment by kosmaa** [comment]
@asitemade4u  Did you created _offices.html template page in /www folder?
I had the same issue because info about template tage was written below code example and wasnt visible at once.

**Comment by asitemade4u** [comment]
My mistake, I had forgotten the "s" in the file name
