### ISSUE TITLE
Error when reordering records in the dashboard

### ISSUE THREAD

**Issue by asitemade4u** [vapid/vapid#24]
Still following the doc.
![image](https://user-images.githubusercontent.com/11460106/45886240-a79aaf80-bd86-11e8-9d7c-746b957fe023.png)

I also lost one record out of three in the process...
Once I also accessed this page (arbitrary.com), for some reason:

![image](https://user-images.githubusercontent.com/11460106/45886314-da44a800-bd86-11e8-93d5-6a96e1c1af5b.png)

**Comment by srobbin** [comment]
Rolling this into #38, since it's got steps to recreate.
