### ISSUE TITLE
Enable CircleCI for pull requests

### ISSUE THREAD

**Issue by DanielRuf** [vapid/vapid#25]
It seems CircleCI is currently not enabled for pull requests and so we cna not see if everything is ok when we create a PR.

**Comment by srobbin** [comment]
@DanielRuf Just saw this after I [commented on your PR](https://github.com/vapid/vapid/pull/22#issuecomment-423704206). I just enabled builds from PRs (I think). Let me know if that does the trick.

**Comment by DanielRuf** [comment]
It did 👍 🎉
