### ISSUE TITLE
Markdown is not recognized in the html type fields

### ISSUE THREAD

**Issue by asitemade4u** [vapid/vapid#26]
I copied and pasted the attached document in the about/body field and I got a text rendering only.
I also tried to drag and drop a *.md file in the editor and the title of the file got input, not its content nor its fully qualified pathway.

[NodeBB+Docker.md.zip](https://github.com/vapid/vapid/files/2405742/NodeBB%2BDocker.md.zip)

![selection_003](https://user-images.githubusercontent.com/11460106/45887275-4de7b480-bd89-11e8-8cc3-6670e2a3f49e.png)

**Comment by srobbin** [comment]
@asitemade4u Just to clarify, is the issue:

1. You enabled Markdown in your about field (e.g. `{{about type=html editor=markdown}}`), and it didn't work.
2. You used the standard HTML tag (e.g. `{{about type=html}}`), and expected Markdown to render when inputted into the WYSIWYG.

Re: drag n' drop, it's not enabled for the editors currently, but that sounds like a useful feature.

**Comment by srobbin** [comment]
@asitemade4u I wanted to check in, and see if you were able to sort this out. If not, let me know the answer to the question above, and/or share your template HTML.
