### ISSUE TITLE
Values do not save properly if there are multiple HTML (Ace) fields on the page

### ISSUE THREAD

**Issue by pjlnmix** [vapid/vapid#29]
Noticed an issue where values were not saving on a dashboard page with multiple Ace editors (markdown & no editor). Steps to reproduce:

1. Create a template or section that contains multiple `html` type fields with either `markdown` or `false` as the editor
2. Attempt to add values to fields and save
3. Add a value to the last field first
4. save
5. attempt to edit the other fields

This will result in other fields either blanking out or inheriting the value added to the last field. Proposed fix in PR #28

**Comment by srobbin** [comment]
Fixed in #28.
