### ISSUE TITLE
Feature request: form action customisation

### ISSUE THREAD

**Issue by kevinruby** [vapid/vapid#31]
It would be nice to have the possibility to change the email form action to another one (custom form endpoint) than Formspree.

Added in a "general settings" section in the dashboard.

Vapid it's a very nice project, thank you!

**Comment by srobbin** [comment]
@kevinruby Were you thinking about hosting the form processor yourself, or is there a Formspree alternative that you're considering? If it's just a matter of submitting the form to another endpoint, I could see us modifying the form directive, so it accepts an "action" parameter. i.e.,

```
{{#form action="https://example.com/form_processor"}}
  {{name}}
  {{email}}
  {{message long=true}}
{{/form}}
```

**Comment by srobbin** [comment]
Also, thanks for the kind words about Vapid! And apologies for the slow reply—I'm on holiday right now, and behind on responding to issues.

**Comment by kevinruby** [comment]
@srobbin Hi, I'm thinking about hosting the form processor myself (a NodeJS backend for example). The "action" parameter would be nice and it's the easiest way.

For an alternative, it would be nice that form isn't just used to contact. It would be nice if we can one day to post comment form or anything saved in the DB. But it's an another feature.

Thank you for the answer.

**Comment by srobbin** [comment]
@kevinruby Just issued a PR for this (#72). It'll go out in the next release. Thanks for the feedback and suggestion.
