### ISSUE TITLE
Feature request: Lists with all records in a multiple-section

### ISSUE THREAD

**Issue by JLKM** [vapid/vapid#34]
Plain html-templates as the workhorse of an entire website setup design and control - database definitions included... Really nice idea! Makes web-publishing much more transparent than usual.

A couple of extra features to consider:
1. `Dynamic lists` showing all records in a multiple-section.
2. `If` and `unless` testing not only for content in a field - but also for presence of a certain string (like `indexOf()`).

**Comment by srobbin** [comment]
@JLKM Thank you.

Can you explain Dynamic Lists a little more? I'm not sure understand.

**Comment by JLKM** [comment]
Sure. I imagine an array of objects containing certain/selected fields from each multiple-section for traversal. This array might be accessible in order to feed a `forall`-method (like `if` and `unless`) - perhaps with a certain upper limit. The result would be a way to create a list of headlines with links for navigation.

**Comment by srobbin** [comment]
@JLKM Thanks for the explanation. If I'm understanding correctly, I think you should be able to do something similar now. For example, let's say you have a repeating section for blog posts:

```
{{#section blog_posts}}
  {{title}}
  {{body type=html}}
{{/section}}
```

And you want to create a sidebar on your homepage with titles/links to the first 5 blog posts. You could do this:

```
<ul>
  {{#section blog_posts limit=5}}
  <li><a href="{{_permalink}}">{{title}}</a></li>
  {{/section}}
</ul>
```

Check out the "Link to Repeating Content" section in the docs for more info: https://docs.vapid.com/learn-more#sections

**Comment by JLKM** [comment]
My bad. Missed that trick in the docs. And my applause for both usefullness and simplicity at the same time.

Still can't get the list to work with three articles, though.

I would expect the nav to the left to show a list with all three articles. But only one - the same as to the right - shows up.

```
  <section>
    <div>
      <div id="nav">
        <ul>
          {{#section articles multiple=true limit=5}}
          <li>
            <h4><a href="{{_permalink}}">{{title}}</a></h4>
            <h5>{{subtitle}}</h5>
          </li>
          {{/section}}
        </ul>
      </div>
      <div id="content" class="container">
        {{#section articles}}
        <h1>{{title}}</h1>
        <h3>{{subtitle}}</h3>
        <h5>Category: {{category}}</h5>
        <strong>{{intro long=true}}</strong>
        {{#if author}}
        <i>{{author}}</i>
        <div class="ui alert message">
          <strong>Author alert: {{author}} on the loose</strong>
        </div>
        {{/if}}
        {{body type=html}}
        {{/section}}
      </div>
    </div>
  </section>
```

![billede](https://user-images.githubusercontent.com/18215374/46036409-b629f380-c105-11e8-80fb-679bbc08fbed.png)

**Comment by srobbin** [comment]
Ah, I see now. That looks like a bug, or rather a shortcoming of the way I designed detail pages. Vapid doesn't know how to pass in an array for the nav section, and a single entry for the content. It's just passing in a single entry for all `#section articles` tags. I'll look into it.

**Comment by JLKM** [comment]
Excellent. Really appreciate your brilliant work.
