### ISSUE TITLE
Deploy To Heroku

### ISSUE THREAD

**Issue by seekersapp2013** [vapid/vapid#37]
I get this error when I try to deploy to heroku, "Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command"

Tried everything but its not working. Please help resolve

**Comment by walidvb** [comment]
Did you try adding a `Procfile` or a `package.json`?

I am guessing heroku doesn't know how to start the app. Try putting this(or similar) in your `Procfile`:

```
web: vapid start
```

**Comment by seekersapp2013** [comment]
I could not find a Procfile but I was able to find a package.json file. So I added the information into that but its still the same. Here is the link to the url http://crunchcorruption.herokuapp.com/

git push heroku
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects:  50% (4/8), 984.00 KWriting objects:  50% (4/8), 1.19 MiBWriting objects:  50% (4/8), 1.46 MiBWriting objects:  50% (4/8), 1.59 MiBWriting objects:  50% (4/8), 1.78 MiBWriting objects:  50% (4/8), 1.85 MiBWriting objects:  50% (4/8), 1.91 MiBWriting objects:  50% (4/8), 2.03 MiBWriting objects:  50% (4/8), 2.10 MiBWriting objects:  50% (4/8), 2.17 MiBWriting objects:  50% (4/8), 2.23 MiBWriting objects:  50% (4/8), 2.43 MiBWriting objects:  50% (4/8), 2.49 MiBWriting objects:  50% (4/8), 2.73 MiBWriting objects:  50% (4/8), 2.80 MiBWriting objects:  50% (4/8), 2.87 MiBWriting objects:  50% (4/8), 3.02 MiBWriting objects:  50% (4/8), 3.13 MiBWriting objects:  50% (4/8), 3.30 MiBWriting objects:  50% (4/8), 3.31 MiBWriting objects:  50% (4/8), 3.33 MiBWriting objects:  50% (4/8), 3.39 MiBWriting objects:  50% (4/8), 3.60 MiBWriting objects:  50% (4/8), 3.66 MiBWriting objects:  50% (4/8), 3.86 MiBWriting objects:  50% (4/8), 3.99 MiBWriting objects:  50% (4/8), 4.16 MiBWriting objects:  50% (4/8), 4.27 MiBWriting objects:  50% (4/8), 4.39 MiBWriting objects:  50% (4/8), 4.53 MiBWriting objects:  50% (4/8), 4.67 MiBWriting objects:  50% (4/8), 4.98 MiBWriting objects:  50% (4/8), 5.16 MiBWriting objects:  50% (4/8), 5.24 MiBWriting objects:  50% (4/8), 5.41 MiBWriting objects:  50% (4/8), 5.62 MiBWriting objects:  50% (4/8), 5.73 MiBWriting objects:  50% (4/8), 5.86 MiBWriting objects:  50% (4/8), 5.88 MiBWriting objects:  50% (4/8), 5.91 MiBWriting objects:  50% (4/8), 5.92 MiBWriting objects:  50% (4/8), 5.94 MiBWriting objects:  50% (4/8), 5.98 MiBWriting objects:  50% (4/8), 6.14 MiBWriting objects:  50% (4/8), 6.20 MiBWriting objects:  50% (4/8), 6.27 MiBWriting objects:  50% (4/8), 6.45 MiBWriting objects:  50% (4/8), 6.52 MiBWriting objects:  50% (4/8), 6.77 MiBWriting objects:  50% (4/8), 6.91 MiBWriting objects:  50% (4/8), 7.02 MiBWriting objects:  50% (4/8), 7.16 MiBWriting objects:  50% (4/8), 7.31 MiBWriting objects:  50% (4/8), 7.54 MiBWriting objects:  50% (4/8), 7.64 MiBWriting objects:  50% (4/8), 7.70 MiBWriting objects:  50% (4/8), 7.82 MiBWriting objects:  50% (4/8), 7.95 MiBWriting objects:  50% (4/8), 8.07 MiBWriting objects:  50% (4/8), 8.14 MiBWriting objects:  50% (4/8), 8.20 MiBWriting objects:  50% (4/8), 8.27 MiBWriting objects:  50% (4/8), 8.34 MiBWriting objects:  50% (4/8), 8.40 MiBWriting objects:  50% (4/8), 8.45 MiBWriting objects:  50% (4/8), 8.58 MiBWriting objects:  50% (4/8), 8.65 MiBWriting objects:  50% (4/8), 8.77 MiBWriting objects:  50% (4/8), 8.90 MiBWriting objects:  50% (4/8), 8.96 MiBWriting objects:  50% (4/8), 9.03 MiBWriting objects:  50% (4/8), 9.09 MiBWriting objects:  50% (4/8), 9.22 MiBWriting objects:  50% (4/8), 9.27 MiBWriting objects:  50% (4/8), 9.41 MiBWriting objects:  50% (4/8), 9.47 MiBWriting objects:  50% (4/8), 9.61 MiBWriting objects:  50% (4/8), 9.66 MiBWriting objects:  50% (4/8), 9.73 MiBWriting objects:  50% (4/8), 9.86 MiBWriting objects:  50% (4/8), 9.92 MiBWriting objects:  50% (4/8), 9.96 MiBWriting objects:  50% (4/8), 10.05 MiWriting objects:  50% (4/8), 10.09 MiWriting objects:  50% (4/8), 10.12 MiWriting objects:  50% (4/8), 10.32 MiWriting objects:  50% (4/8), 10.41 MiWriting objects:  50% (4/8), 10.53 MiWriting objects:  50% (4/8), 10.63 MiWriting objects:  50% (4/8), 10.70 MiWriting objects:  50% (4/8), 10.84 MiWriting objects:  50% (4/8), 10.97 MiWriting objects:  50% (4/8), 11.23 MiWriting objects:  50% (4/8), 11.33 MiWriting objects:  50% (4/8), 11.45 MiWriting objects:  50% (4/8), 11.52 MiWriting objects:  50% (4/8), 11.58 MiWriting objects:  50% (4/8), 11.62 MiWriting objects:  50% (4/8), 11.71 MiWriting objects:  50% (4/8), 11.84 MiWriting objects:  50% (4/8), 12.02 MiWriting objects:  50% (4/8), 12.28 MiWriting objects:  62% (5/8), 12.28 MiWriting objects:  75% (6/8), 12.28 MiWriting objects:  87% (7/8), 12.28 MiWriting objects:  87% (7/8), 12.35 MiWriting objects: 100% (8/8), 12.35 MiWriting objects: 100% (8/8), 12.36 MiB | 106.00 KiB/s, done.
Total 8 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.12.0...
remote:        Using default npm version: 6.4.1
remote:
remote: -----> Restoring cache
remote:        Cached directories were not restored because of a change in versions of node, npm, or yarn
remote:        Module installation may take longer for this build
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote:        > bcrypt@2.0.1 install /tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/bcrypt
remote:        > node-pre-gyp install --fallback-to-build
remote:
remote:        [bcrypt] Success: "/tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
remote:
remote:        > sqlite3@4.0.2 install /tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/sqlite3
remote:        > node-pre-gyp install --fallback-to-build
remote:
remote:        [sqlite3] Success: "/tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" is installed via remote
remote:
remote:        > node-sass@4.9.3 install /tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/node-sass
remote:        > node scripts/install.js
remote:
remote:        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-57_binding.node
remote:        Download complete
remote:        Binary saved to /tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/node-sass/vendor/linux-x64-57/binding.node
remote:        Caching binary to /tmp/npmcache.eByOy/node-sass/4.9.3/linux-x64-57_binding.node
remote:
remote:        > node-sass@4.9.3 postinstall /tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/node-sas
remote:        > node scripts/build.js
remote:
remote:        Binary found at /tmp/build_45115fe6c4e3df9d7e37699f975b812d/node_modules/node-sass/vendor/linux-x64-57/binding.node
remote:        Testing binary
remote:        Binary is fine
remote:        added 1191 packages from 799 contributors and audited 7492 packages in 41.914s
remote:        found 1 low severity vulnerability
remote:        run `npm audit fix` to fix them, or `npm audit` for detail
remote:
remote: -----> Caching build
remote:        - node_modules
remote:
remote: -----> Pruning devDependencies
remote:        audited 7492 packages in 10.132s
remote:        found 1 low severity vulnerability
remote:        run `npm audit fix` to fix them, or `npm audit` for detail
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote:
remote: -----> Compressing...
remote:        Done: 58.2M
remote: -----> Launching...
remote:        Released v7
remote:        https://crunchcorruption.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/crunchcorruption.git
   27e8f0d..d5a8488  master -> master

**Comment by seekersapp2013** [comment]
And on heroku dashboard I noticed that instead of having web: vapid start it has web: npm start. But I was unable to edit this information.

**Comment by seekersapp2013** [comment]
Tried using both but still not working. 

Can you please create a working demo on github, add heroku deploy button, then let's see.

Maybe a system configuration on my part is the problem. 

Thanks

**Comment by walidvb** [comment]
hm apologies. Indeed, it doesn't seem as straight-forward as hoped for. Don't really have the time to check all this right this second unfortunately.

**Comment by seekersapp2013** [comment]
And I have put in a lot of work to start all over. Please consider.

**Comment by walidvb** [comment]
I will let an admin answer, but you are using beta software, and should be wary of not relying too critically on it.

One thing you might want to try, if you can't figure heroku out, is to Dockerize it, perhaps that will work. I'm not sure of the internals of heroku.
Other options include self-hosting, of course.

**Comment by trst** [comment]
Interesting. I gave it a go and Heroku logs say that the crash was caused by an SQLite error: unable to open database file. @seekersapp2013 perhaps you could look through your `heroku logs` to check for what crashed your instance. If its the same we can put more weight behind this issue 😄

A snippet of my log file posted below:

```
2018-09-25T16:47:58.000000+00:00 app[api]: Build succeeded
2018-09-25T16:48:06.303328+00:00 heroku[web.1]: Starting process with command `vapid start .`
2018-09-25T16:48:25.584807+00:00 heroku[web.1]: State changed from starting to crashed
2018-09-25T16:48:25.549530+00:00 heroku[web.1]: Process exited with status 1
2018-09-25T16:48:25.320617+00:00 app[web.1]: ==> Starting the production server...
2018-09-25T16:48:25.465708+00:00 app[web.1]: ERROR: SQLITE_CANTOPEN: unable to open database file
2018-09-25T16:48:25.896247+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=stark-inlet-33938.herokuapp.com request_id=d2a3d0fb-0b7f-40d9-b5ba-ba19ca878e96 fwd="172.103.181.5" dyno= connect= service= status=503 bytes= protocol=https
2018-09-25T16:48:26.774056+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=stark-inlet-33938.herokuapp.com request_id=9a6137f6-ee15-42ee-9f21-6cca757c4850 fwd="172.103.181.5" dyno= connect= service= status=503 bytes= protocol=https
2018-09-25T16:48:27.574620+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=stark-inlet-33938.herokuapp.com request_id=0c9cffc3-89c2-4455-8355-5a915819c6f7 fwd="172.103.181.5" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by srobbin** [comment]
@seekersapp2013 I just added a Wiki doc yesterday that might be helpful:

https://github.com/vapid/vapid/wiki/Self%E2%80%90hosting

Did you add the `SECRET_KEY` env variable to Heroku?

```
heroku config:set SECRET_KEY= supersecret
```

**Comment by srobbin** [comment]
@seekersapp2013 Were you able to successfully deploy on Heroku? 

In any case, I'd like to move conversations about deployment issues over to the [Vapid forums](https://forums.vapid.com/). Please feel free to chime in over there, and update me on the progress of deploying to Heroku, or provide tips to others facing the same issue. Thanks.
