### ISSUE TITLE
Reordering new records in sortable sections fails

### ISSUE THREAD

**Issue by ohnoimdead** [vapid/vapid#38]
## Repro

* vapid new foo
* update index.html to add a new sortable section
* on the dashboard, add two new records for that section (let's say "one" and "two")
* drag the bottom record to the top (drag "one" to the top of the list)

## Expected

The dashboard and the site (and the db) match ordering.

## Actual

The dashboard shows "one" first but the site shows "two" first.

## Notes

Starting with a new section we add a new record "one", we have:

```
sqlite> select content, position from records;
{"repro":"one"}|0
```

then we add "two":

```
sqlite> select content, position from records;
{"repro":"one"}|0
{"repro":"two"}|0
```

At this point the dashboard is showing "two" first and "one" second. So we drag "one" to the top of the list and then we see this:

```
sqlite> select content, position from records;
{"repro":"one"}|1
{"repro":"two"}|0
```

Which is not correct. Refreshing the dashboard resets the UI order and reordering will work correctly up until a new record is added.

When new records are created in sortable sections they are given a position of 0 but the rest of the records associated with that section are not reordered, which results in this behavior. However, if the rest of the records are reordered then adding new records will take linearly longer as the list gets longer. A potential fix would be to use reverse ordering so that new records are always added with a position of length_of_section+1 and then the dashboard and site display the items in descending order. There might be other better options.

There a secondary related issue which creates gaps in the ordering - ordering forward shifts position up by 1 which means ordering forward then ordering backward creates an ordering gap. To see this in action create three records in a section and then move the top item to the bottom several times then move the bottom item up one. You'll see something like:

```
sqlite> select content, position from records;
{"repro":"one"}|4
{"repro":"two"}|7
{"repro":"three"}|6
```

This doesn't cause any visible issues I could see but I bet there are good reasons you don't want this.

**Comment by srobbin** [comment]
Thanks, @ohnoimdead. This info is super helpful. I'll look into it.
