### ISSUE TITLE
Does Vapid support switching languages?

### ISSUE THREAD

**Issue by joyobject** [vapid/vapid#41]
I'm now the process of testing Vapid and I'm very impressed by how easy we I can set up (I'm a designer) However, my clients would like to have 2 languages on her site. The dashboard is ok to be one language but the site should be able to support 2 languages.

**Comment by gadd-ferreira** [comment]
@srobbin is looking at it, we are currently drafting the spec here: #19

**Comment by joyobject** [comment]
@gadd-ferreira thank you
