### ISSUE TITLE
Add vapid build command

### ISSUE THREAD

**Issue by Jack89ita** [vapid/vapid#42]
Hi! i think that it will be nice to have a ```vapid build``` command. Currently there's only ```vapid deploy```, that is used to deploy on vapid hosting, but what if i would like to deploy to my own server minifing and building the site?
Woult it be possible?
Thanks

**Comment by srobbin** [comment]
@Jack89ita Thanks for submitting this request. I'm going to close this issue and consolidate it with #9, since it's a similar topic. Feel free to chime in there.
