### ISSUE TITLE
Add a helper to show an active state for navigation

### ISSUE THREAD

**Issue by ramijames** [vapid/vapid#47]
I realize that this means including some sort of routing, and that perhaps another package can be used for this (vue.js, for example) but it would be helpful to have it in a simpler form. It might be enough to be able to just query the URL.

**Comment by walidvb** [comment]
I think a nice workaround for this would be to pass variables to partials, currently discussed in #66 :

```
# www/_menu.html
<a href="subpage" class="{#if subpage}active{/if}">subpage</a>
```

```
# www/subpage.html
{> menu subpage=true}
```
