### ISSUE TITLE
cant do anything

### ISSUE THREAD

**Issue by dthreatt** [vapid/vapid#48]
I tried on ubuntu for windows and cloud9 and cannot even get the vapid new /path/to/project to work
!

[2018-09-27 13_26_10-vapid - cloud9](https://user-images.githubusercontent.com/8387791/46172849-6a885e80-c259-11e8-9b71-16a707120b8b.png)

**Comment by srobbin** [comment]
@dthreatt Sounds like you're having the same issue described in #45. You'll need to update to Node.js v8.9.0 or greater to install Vapid.

Closing this ticket. If you have any follow-up questions, please add them to #45.
