### ISSUE TITLE
Extending Vapid - Custom Scripts, Extensions, Hooks, etc.

### ISSUE THREAD

**Issue by iocron** [vapid/vapid#49]
Is there a possiblity to extend the logic of vapid with own scripts, writing extensions/plugins for it, etc.? Does Vapid provide any hooks to add own code as well? I love the cms and the features of it very much, I am just missing some possibilities to extend it (e.g. adding own content types, plugins, etc.).

**Comment by srobbin** [comment]
@iocron Thanks for bringing this up—it's a great question. I just created a new Issue (#57) that summarizes similar thoughts and asks a few open-ended questions about what types of plugins folks would like to develop. Please feel free to join in there.
