### ISSUE TITLE
Get index of item in list

### ISSUE THREAD

**Issue by Jack89ita** [vapid/vapid#51]
Hi! would it be possible to get the index of the current item while looping a list with this tag ```{{#section officesList multiple=true sortable=true}}```
It will be useful for conditional statement and maybe classes personalizations.
Thank you very much!

**Comment by srobbin** [comment]
@Jack89ita Right now, there's no way to access the current index of a loop, but it probably wouldn't be too hard to add. That said, conditional statements (`#if` and `#unless` directives) don't test for equality, just the presence or absence of a value. Given that, can you think of another use case for the index?

**Comment by walidvb** [comment]
if it's only for class modifier, would CSS pseudo-classes not do the trick?

**Comment by Jack89ita** [comment]
@walidvb I think you are right. I will close this, thank you all!
