### ISSUE TITLE
WYSIWYG editor should support multiple paragraphs

### ISSUE THREAD

**Issue by tealtan** [vapid/vapid#53]
I was expecting the html content type (using the wysiwyg editor) to support outputting multiple paragraphs instead of a single chunk of html separated by `<br/>`s.

(I can get that to happen when using the markdown editor, but it would be nice if the wysiwyg option did that as well.)

Maybe this is already supported?

**Comment by srobbin** [comment]
@tealtan Agreed.

Right now, we're using the [Trix editor](https://github.com/basecamp/trix), which has a great, simple interface, but creates the markup you described. There have been a [couple](https://github.com/basecamp/trix/issues/117) of [discussions](https://github.com/basecamp/trix/issues/202) in the Trix repo about modifying the output, but it doesn't look like there are plans to move forward.

Do you have a WYSIWYG editor that you like? I've been eyeing a couple of them as replacements:

https://summernote.org/
https://quilljs.com/

**Comment by tealtan** [comment]
@srobbin Quill looks quite nice! I’ve also seen https://prosemirror.net, which has both WYSIWYG and markdown modes.

**Comment by srobbin** [comment]
@tealtan Ooh, ProseMirror looks nice. I'll dig into it some more, thanks.

**Comment by seekersapp2013** [comment]
I would suggest codemirror. https://codemirror.net/

**Comment by srobbin** [comment]
@tealtan The new WYSIWYG is live now, with `<p>` tags instead of `<div><br>`.
