### ISSUE TITLE
Is there any tutorial on self-hosting Vapid?

### ISSUE THREAD

**Issue by joyobject** [vapid/vapid#54]
I have tested Vapid on my mac without any problem. So now I'd like to deploy the site on the server. I have set up a clean new Droplet in Digital ocean. The follow is what I did for the setup:

- Ubuntu 18.04 x64 
- NodeJS v8.10.0
- Nginx 
With the Nginx default setup, the public site should be in /var/www/html 
My question is that what is my next step? Should I install Vapid on my server? using `npm install -g vapid-cli`? 
I believe that I don't need to do this `vapid new path/to/project/folder` because I already have a file on my local computer. 
how can I deploy from my local to the the server? (I have ssh access to the server). 

Thank you

**Comment by joyobject** [comment]
I think the common way to do is to push the Vapid folder to github. And go to Digitalocean droplet and clone Vapid folder from github to the server. But I am not sure about the database. (the data folder). Thank you

**Comment by trst** [comment]
It would be nice to for clear documentation on deploying SQLite because being able to keep the database in sync through git would be an easier way to get developers involved with Vapid and reduce barrier to entry at the expense of robustness.

Leave the option to switch database types for those who need it.

**Comment by srobbin** [comment]
Theoretically, you shouldn't have to do _anything_ to deploy with SQLite—the app creates the database on startup if one doesn't already exist. So, if you deploy a vanilla Vapid project to production, it should just work, database-wise.

**Comment by trst** [comment]
Interesting. I’ll have to test again. I had issues earlier after deployment but it might have been my server.

Is it worth adding a section to the documentation?

**Comment by srobbin** [comment]
@joyobject Any luck getting it to run on DigitalOcean?

In any case, I'd like to move conversations about deployment issues over to the [Vapid forums](https://forums.vapid.com/). Please feel free to chime in over there, and update me on the progress of your droplet deploy, and provide tips to others in the same boat.
