### ISSUE TITLE
Enable template tags on 404 page

### ISSUE THREAD

**Issue by Jack89ita** [vapid/vapid#55]
Hello! would it be possible to enable the use of template tags on 404 page?
Thank you!

**Comment by srobbin** [comment]
@Jack89ita I'm curious to hear how you'd use them. Currently, we're not running error pages through the parser, to ensure that they'll always display without issue. I'm open to the idea of parsing the 404 page, but I'd like to hear a little more first.

**Comment by Jack89ita** [comment]
Well i would use the template tags to print common parts of my website like header or footer. Or maybe dynamic parts like menu. Do you think this could be a good idea?
Thanks!

**Comment by Jack89ita** [comment]
Hey @srobbin what do you think about this? Would it be possible?

**Comment by srobbin** [comment]
@Jack89ita Possibly. Right now, I'm focused on bug fixes and stability, but I'll keep in it mind for a future release.

**Comment by Jack89ita** [comment]
Hello again @srobbin. In a few days i will publish my work (probably in winners awards too), and for sure i will need the 404 page customized. Do you know when this feature will be available? Or do you accept PR for this?
Thank you.

**Comment by srobbin** [comment]
@Jack89ita Congrats on the upcoming launch—I'm looking forward to seeing what you build.

Unfortunately, I don't think this feature will be released in the next few days, possibly not for a few months. I'm leaving feature requests like these open for now, allowing others to participate before we move ahead.

**Comment by Jack89ita** [comment]
@srobbin i see, So the only solution it to put static content into 404 page right?

**Comment by srobbin** [comment]
@Jack89ita That's correct, for now.

**Comment by JohJakob** [comment]
Hello @srobbin! Could you reopen this issue please? I would like to do exactly what @Jack89ita wanted to do on the custom error page. The website visitor should be able to access things like a dynamic navigation menu or the footer from the 404 error page. With the current solution, the developer is forced to update that every time a change is made to it in the dashboard.
