### ISSUE TITLE
ERROR: Cannot find module

### ISSUE THREAD

**Issue by cece554** [vapid/vapid#58]
I've been using vapid just fine, but now when i try to start a new project i get the error ERROR: Cannot find module 'path/to/folder'.

i uninstalled vapid then re installed to see if that would make a difference but it did not.

**Comment by srobbin** [comment]
@cece554 Sounds like it's having a hard time finding your project. If you know where your project is located, you can navigate to the directory first, and then start Vapid.

```
cd /Users/example/Desktop/project
vapid start .
```

is the same as doing

```
vapid start /Users/example/Desktop/project
```

**Comment by cece554** [comment]
you're right i must be tired, lol i copied the wrong file path.
sorry to bother
