### ISSUE TITLE
Multiple fields

### ISSUE THREAD

**Issue by walidvb** [vapid/vapid#6]
Wondering how to add multiple images to a single section?
Pointers to where that should be changed are appreciated, would love to take a look when i find a moment if it's not a priority! From what I quickly gathered:

 - update `BaseDirective.input` to allow an 'Add more' button
 - update `BaseDirective.serialize` to return an array of values if multiple inputs

awesome job on the rest, and awesome idea, thanks!

**Comment by srobbin** [comment]
@walidvb: I can see how this would be useful, but there are some feature requests that might resolve to a different solution, and a temporary workflow to handle the existing need.

Regarding a temporary workflow, it's possible to use a second section to handle multiple images/fields. For example:

```
{{#section about}}
  <h2>About Us</h2>
  {{#section about_slideshow multiple=true}}
    {{photo type=image}}
  {{/section
{{/section}}
```

In terms of related feature requests, here are a few proposals being discussed:

**Nested Sections (#12)**
The ability to nest "Slideshow" under "About Us" in the nav.

**Custom Directives (#57)**
Allowing custom directives should give you the ability to extend Vapid, and create a multi-image plugin. I'll address the comment you've made in that thread there, directly, but for readability's sake I'll summarize here: I think it's fine if people decide to make presentational directives. I agree that they don't have a place in core; custom directives would give people the freedom to move in any direction that suits their needs, regardless of how it fits into Vapid's ethos.

**Content alias / reference (#60)**
If I understand this one correctly, they'd like to be able to reference one section from another. e.g., `{{#section blog_posts}} can reference `{{#section categories}}`.

**Comment by walidvb** [comment]
I see the work around. Multiple fields sounds pretty basic functionality(no less than other mentions). Curious to hear other opinions, and guess this decision will be left to #57

**Comment by martonlente** [comment]
Thanks @walidvb for confirming this. I think it could be a simple, but good solution for many ideas of #57 too.

**Comment by walidvb** [comment]
Come to think of it, fieldsets are more relevant to nested sections in #12, I think.
Multiplicating one unique field also requires a much different UI rendering, I imagine.

**Comment by martonlente** [comment]
I think it's really worth having a look on how it's implemented in Perch CMS, even if Vapid is a completely different product, as it's so close to how sections actually work: [https://youtu.be/QWm_gjcGSFo](url). Craft CMS has a similar feature too, so it's a feature not specific to a certain CMS.

**Comment by martonlente** [comment]
Hello!

Are there any updates/plans on this? This feature would make Vapid so much more capable! Thanks for considering.

**Comment by Voydfox** [comment]
I'm working on a project right now in VAPID and got to a point where I needed this only to find out it's not possible. Dang! VAPID is pretty slick, would love to see this implemented. <3

**Comment by geeworthington** [comment]
> I'm working on a project right now in VAPID and got to a point where I needed this only to find out it's not possible. Dang! VAPID is pretty slick, would love to see this implemented. <3

@Voydfox - The functionality is there dude..

Check the documentation.

`<ul>
  {{#section offices multiple=true}}
    <li>
      <h5><a href="{{_permalink}}">{{name}}</a></h5>
      {{city}}, {{state}}
    </li>
  {{/section}}
</ul>`

**Comment by JohJakob** [comment]
> @walidvb: I can see how this would be useful, but there are some feature requests that might resolve to a different solution, and a temporary workflow to handle the existing need.
> 
> Regarding a temporary workflow, it's possible to use a second section to handle multiple images/fields. For example:
> 
> ```
> {{#section about}}
>   <h2>About Us</h2>
>   {{#section about_slideshow multiple=true}}
>     {{photo type=image}}
>   {{/section
> {{/section}}
> ```
> 
> In terms of related feature requests, here are a few proposals being discussed:
> 
> **Nested Sections (#12)**
> The ability to nest "Slideshow" under "About Us" in the nav.
> 
> **Custom Directives (#57)**
> Allowing custom directives should give you the ability to extend Vapid, and create a multi-image plugin. I'll address the comment you've made in that thread there, directly, but for readability's sake I'll summarize here: I think it's fine if people decide to make presentational directives. I agree that they don't have a place in core; custom directives would give people the freedom to move in any direction that suits their needs, regardless of how it fits into Vapid's ethos.
> 
> **Content alias / reference (#60)**
> If I understand this one correctly, they'd like to be able to reference one section from another. e.g., `{{#section blog_posts}}` can reference `{{#section categories}}`.

I would appreciate a `multiple` parameter for the image content type and maybe for the text content type as well. Making a separate section for, let’s say, an image gallery seems counterintuitive. The `multiple` parameter could tell Vapid to render an unordered list. This would be really helpful if you’re making a portfolio website for example.

**Comment by walidvb** [comment]
@geeworthington this is for multiple sections, this thread is about having multiple fields. So, offices would be a `{#section multiple}`, but would have a list of `{employees multiple}`, see?
