### ISSUE TITLE
Self Hosting install

### ISSUE THREAD

**Issue by cece554** [vapid/vapid#61]
I'm having trouble installing on my site a centos7 Digital Ocean droplet. 

Ive installed Node.js via
`sudo yum install epel-release`
`sudo yum install nodejs`
`sudo yum install npm`

then tried to install vapid
using 
`npm install -g vapid-cli`

got these errors
pm ERR! Linux 3.10.0-862.2.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "vapid-cli"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

tried using sudo and got these errors
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
Killed         ....] - extract:electron-to-chromium: sill gunzTarPerm extractEn

**Comment by Jack89ita** [comment]
What version of node.js are you using?
In the documentation you can read "Vapid requires node v8.9.0 or higher".

**Comment by siriokun** [comment]
Try install with sudo, 

 ```sh
sudo npm install -g vapid-cli
```

**Comment by srobbin** [comment]
I agree with @Jack89ita, looks like it's an issue with the version of Node:

> npm ERR! node v6.14.3

If you still need assistance, can you please open a thread on the [Vapid forums](https://forums.vapid.com/)? I'm hoping to steer questions about installation, hosting, and general use of Vapid to the forums, and reserve GitHub issues for software development and bugs. Thanks.
