### ISSUE TITLE
npm install -g vapid-cli error on linux

### ISSUE THREAD

**Issue by seekersapp2013** [vapid/vapid#64]
Trying to install vapid on linux but get this error. I don't know what the problem may be please help

**Describe the bug**
Vapid outputs an error after vapid start or vapid new is fired. 

**To Reproduce**
1. Install nodejs on my server using SSH
2. then npm install -g vapid-cli
3. vapid new path/to/project/folder or vapid new

**Expected behavior**
The app was supposed to create a new app with vapid new

**Screenshots**
![bug-02](https://user-images.githubusercontent.com/5487558/46482462-8b1e5e80-c7ed-11e8-879b-018079768d89.png)

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: [Linux CPanel]
 - Browser [Chrome]
 - Node Version [10]
 - Vapid Version [e.g. 0.1.24, found in package.json]

**Comment by srobbin** [comment]
@seekersapp2013 I'm sorry to hear you're having trouble installing Vapid. I'm going to close this issue, and reply to you on [your post in the forums](https://forums.vapid.com/t/npm-install-g-vapid-cli/30).
