### ISSUE TITLE
Automatic responsive image / thumbnail generation on upload

### ISSUE THREAD

**Issue by w-biggs** [vapid/vapid#65]
**Is your feature request related to a problem? Please describe.**
Images uploaded through the dashboard are uploaded in full quality. When displaying those full quality images, load times are heavily impacted if the images are too large. I have a small gallery on a website I'm building that is affected by this and would greatly benefit from generated thumbnails.

**Describe the solution you'd like**
In the dashboard, a user could upload an image, and that image would automatically be processed and resized to multiple sizes. Maybe this could be a flag, and maybe the image sizes could be flags as well. If it is a flag, it might be nice to have that flag also automatically use srcset for those sizes? A hypothetical example:
```
{{image
    type=image
    responsive=true
    sm=320px
    md=480px
    lg=800px
    sizes="(max-width: 320px) 280px,
            (max-width: 480px) 440px,
            800px"
}}
```
turns into
```
<img srcset="image-sm.jpg 320w,
             image-md.jpg 480w,
             image-lg.jpg 800w"
     sizes="(max-width: 320px) 280px,
             (max-width: 480px) 440px,
             800px"
     src="image-orig.jpg">
```
Alternately, maybe it could be something like this:
```
<img srcset="{{image type=image size=320px tag=false}} 320w,
             {{image type=image size=480px tag=false}} 480w,
             {{image type=image size=800px tag=false}} 800w"
     sizes="(max-width: 320px) 280px,
             (max-width: 480px) 440px,
             800px"
     src="{{image type=image size=orig tag=false}}">
```
becoming
```
<img srcset="image-320px.jpg 320w,
             image-480px.jpg 480w,
             image-800px.jpg 800w"
     sizes="(max-width: 320px) 280px,
             (max-width: 480px) 440px,
             800px"
     src="image-orig.jpg">
```

**Describe alternatives you've considered**
While #11 has been suggested, it's not currently possible; in addition, this seems like something that would affect a large enough number of users that inclusion with Vapid might be preferable. One could also have multiple image uploads for each section, which is my current workaround, but this is a bit clunky and my clients might not have the ability or knowledge to create multiple sizes of every image they upload.

**Additional context**
None I can think of. Thanks!

**Comment by srobbin** [comment]
@w-biggs Yeah, I think this would be useful. @nazhamid and I had been discussing something similar: adding image processing for creating thumbnails. In our context, it was about cropping (e.g. `{{photo type=image width=100 height=100 crop=true}}`), but this sounds like another good use case.

With both in mind, I could see it working similar to your second example. Maybe something like this:

```
<img srcset="{{image type=image width=300 tag=false}} 320w,
             {{image type=image width=480 tag=false}} 480w,
             {{image type=image width=800 tag=false}} 800w"
     sizes="(max-width: 320px) 280px,
             (max-width: 480px) 440px,
             800px"
     src="{{image type=image tag=false}}">
```

Where directive was smart enough to understand that setting the width only means you wanted to preserve the aspect ratio. What do you think?

**Comment by w-biggs** [comment]
Yeah, I think that'd cover most use cases and make the most sense.

**Comment by trst** [comment]
I had something very similar in mind. Image manipulation would be huge for generating srcsets automatically. This is perhaps another feature (or plugin) all together, but being able to dial in compression/quality would be helpful.

Sincerely,
Steven Teskey

**Comment by srobbin** [comment]
I wanted to let you all know that PR #106 is nearly ready to merge, and should allow you to should cover most of these scenarios.
