### ISSUE TITLE
Click addEventListener doesn't work on anchor links

### ISSUE THREAD

**Issue by Tibo46** [vapid/vapid#67]
**Describe the bug**
Hello,
I just found out that the click event listener doesn't work on anchor links.
Other listener such as "mouseover" and "mouseout" works fine. My best guess is that it's an issue with the routing mechanism.

**To Reproduce**
### HTML 
`<a href="#" class="link-nav">My Link</a>`
### JS 
`
function myFunction() {
    alert('clicked');
}
document.querySelector('.link-nav').addEventListener('click', myFunction);
`

**Expected behavior**
The alert should popup when clicking on the link.

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: Windows 10
 - Browser Chrome 69
 - Node v10.9.0
 - Vapid ^0.1.24

**Comment by srobbin** [comment]
@Tibo46 From the code above, it looks like `document.querySelector('.link-nav')` just needs to be changed to `document.querySelector('.nav-link')`.

**Comment by Tibo46** [comment]
@srobbin my bad was a bad copy and paste of the example. That's not solving the issue

**Comment by w-biggs** [comment]
Your code is working perfectly for me, and I'm not sure what Vapid could do to prevent this from working. Are there any error messages showing up? Is there any other JS on your page?

**Comment by Tibo46** [comment]
Wow sorry i was being really stupid... Looks like i had another item with that classname somewhere and so the event listener wasn't attached to all of them...
My bad

**Comment by srobbin** [comment]
@Tibo46: happens to me all the time. Glad to hear it’s resolved.
