### ISSUE TITLE
Default site template headline looks strange by default on wide monitors

### ISSUE THREAD

**Issue by janpio** [vapid/vapid#7]
Win 10, FF62:
![image](https://user-images.githubusercontent.com/183673/45814499-18ce5a00-bcd6-11e8-84fc-58a5a9a5e012.png)

Just changed "greeting" to `...`. 

Looks ok up until ~1390 width, then the main headline stays at the same position instead of staying centered.

**Comment by sushaantu** [comment]
It's a simple fix though. Just give "margin: 0 auto;" to .header h1 on line 95 of site.css
