### ISSUE TITLE
Alter Form Elements HTML

### ISSUE THREAD

**Issue by JohannesHoffmann** [vapid/vapid#70]
If you are using a css framework for example bulma or bootstrap you have to use their html structure in forms. A nice feature would be to provide a way to change the default html given by vapid of all form elements.

My first idea: Create an folder **_form** with files **_form/_text.html** or **_form/_password.html** and so on.

**Comment by srobbin** [comment]
@JohannesHoffmann Thanks for the suggestion.

In cases like these, I think it might be better to bypass Vapid's form tag, and use Formspree directly (i.e., `{{#form}}` is just a convenience wrapper around Formpree).

https://formspree.io/

**Comment by JohannesHoffmann** [comment]
Well that's right ;) - thank's for the work!
