### ISSUE TITLE
Impossible to start a new project

### ISSUE THREAD

**Issue by watermelon-pixels** [vapid/vapid#73]
Hi,

**Bug**
Impossible to start a project with vapid. :/
```
AppData\Roaming\npm\node_modules\vapid-cli\bin\cli.js:14
  return async (target) => {
               ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**My Environment**
 - Windows 7
 - Browser [e.g. Chrome, Safari]
 - Node v6.9.5
 - Vapid Last one

**Comment by Jack89ita** [comment]
From the doc: "Vapid requires node v8.9.0 or higher, and can be installed via npm"

**Comment by watermelon-pixels** [comment]
OK @Jack89ita, Thanks.
I done the upgrade.
I created an Vapid project.
But I can't run it by _vapid_ _start_ task.
`ERROR: Please install sqlite3 package manually`

I install npm sqlite3 locally. But it doesn't work.

**Comment by Jack89ita** [comment]
Try to read [this](https://forums.vapid.com/t/installation-problems/35/7), but it is relate to a Mac OS.
Better wait for @srobbin sorry,

**Comment by srobbin** [comment]
@watermelon-pixels It sounds like you're having a similar issue to the one @Jack89ita linked to.

Try deleting the contents of "node_modules" then reinstalling the packages. i.e.:

```
cd /path/to/your/project
rm -rf node_modules
npm install
npm start
```

If that doesn't work, please join the discussion on our forums: https://forums.vapid.com/t/installation-problems/35/7

**Comment by watermelon-pixels** [comment]
Ok thank @srobbin
