### ISSUE TITLE
Using Vapid with Vue.js

### ISSUE THREAD

**Issue by alecmarcus** [vapid/vapid#78]
Hi all, I'm super excited about Vapid. Up front, I've not dealt much with CMS before, and I figured it would be a great point of entry for me. My development experience is almost all front-end.

And so, I'll be the first to ask it: 

How would I get up and running using Vapid with Vue.js? 
---
I usually initialize my Vue projects with either `vue-cli`, or I use Nuxt, which spoils me and sets everything up. As I understand it, Nuxt, being a SSR framework, wouldn't play nicely with Vapid, so I'm going with plain Vue. 

My guess is that I'll want to be passing the contents of `dist` to Vapid, essentially as a replacement for the `www` folder that `vapid-cli` creates. As I've never done this before though, I don't know if that's actually correct, and I'm just playing around at the moment to see what I can learn.

Some specific questions I have:
---
* Where/how is webpack configured in projects created using `vapid-cli`?
* Would the `vapid start` command and associated script replace the `npm run serve` script I usually use while developing Vue apps?
* Will Vapid work running Vue in SPA mode?
* Should I try to configure webpack to build my Vue files and components into `www` (essentially replacing `dist`)?

I'd really appreciate even just a point in the right direction. Thanks!

**Comment by srobbin** [comment]
@alecmarcus I see you started [a topic in the forums](https://forums.vapid.com/t/vapid-and-vue-js/72)—thank you. That's a good place for us to discuss Vapid and Vue, and hopefully, others can jump in. I'm going to close this issue, and reply in the forum thread.
