### ISSUE TITLE
Change out Node-Sass for Dart-Sass

### ISSUE THREAD

**Issue by Hadr619** [vapid/vapid#83]
**Is your feature request related to a problem? Please describe.**
Currently in the project you are using ```node-sass``` for sass compiling. Since ```libsass``` is deprecated basically so is node-sass and it would be nice to use a sass that was up to date with releases. 

**Describe the solution you'd like**
Changing the compiling sass to ```Dart-Sass``` would allow users to use and be up to date with sass features and get away from a lot of errors and headaches that revolve around the use of ```node-sass```

**Describe alternatives you've considered**
Any alternatives are staying with ```node-sass```. Which, even though it works, may not be ideal in the long run.

**Comment by srobbin** [comment]
Thanks, @Hadr619. I've got a pull request ready for this one—it'll ship in the next release.
