### ISSUE TITLE
Failed to install on Node v10

### ISSUE THREAD

**Issue by siriokun** [vapid/vapid#88]
Vapid failed to install on Node v10.

**To Reproduce**
1. Install NodeJS version 10
2. `npm install -g vapid-cli`
3. `vapid new site`
4. `vapid start site`

**Result**
```sh
ERROR: The module '\\?\C:\Users\rio\AppData\Roaming\npm\node_modules\vapid-cli\node_modules\bcrypt\lib\binding\bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Environment**
 - OS: Windows 10 x64
 - Node Version : 10.13.0
 - Vapid Version : 0.2.2

**Comment by srobbin** [comment]
@siriokun I'm sorry to hear that you're having trouble installing Vapid. Would you mind opening a new thread on the [Vapid forums](https://forums.vapid.com/)? We're trying to address install and usage issues there, and keep GitHub for development-oriented tasks. Thanks.
