### ISSUE TITLE
Firefox - html5sortable redirects to www.arbitrary.com

### ISSUE THREAD

**Issue by JohannesHoffmann** [vapid/vapid#90]
**Describe the bug**
Sorting a Element of a Section with multiple=true and sortable=true to the end of the list redirects from Vapid backend to www.arbitrary.com.

Known issue and already fixed in html5sortable library: https://github.com/lukasoppermann/html5sortable/issues/450

Only happens on Firefox. Safari works fine.

**To Reproduce**
1. Create Section with multiple=true and sortable=true
2. Create at least 3 elements
3. Sort elements to bottom
4. After the second try your browser redirects to: www.arbitrary.com

**Expected behavior**
Stay on the Vapid-Backend and sort the element on the right place.

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: OSX
 - Browser Firefox
 - Node Version v10.12.0
 - Vapid Version 0.2.2

**Comment by srobbin** [comment]
@JohannesHoffmann Thanks for letting me know about this. I just issued a PR for the fix—it'll go out in the next release.
