### ISSUE TITLE
Unable to apply CSS or load JS files when deploying to Vapid

### ISSUE THREAD

**Issue by vascogaspar** [vapid/vapid#93]
Hi. I'm having trouble deploying my first site with Vapid.
Seems like the CSS and JS files are not being applied/uploaded when self hosting using `vapid deploy`.
Everything works fine while on development.

**From the console**: `Refused to apply style from 'https://XPTO.vapid.site/stylesheets/site.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`.
Also javascripts/site.js cannot be found (404).
Other assets are being uploaded correctly into Vapid CDN.

**My folder structure**
```
www/
  index.html
  javascripts/
    site.pack.js
  stylesheets/
    site.pack.scss
    ...
  images/
    ...
  sounds/
    ...
  fonts/
    ...
```

**My index.html import tags**
`<link rel="stylesheet" type="text/css" href="/stylesheets/site.css">`
`<script src="/javascripts/site.js"></script>`

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: OS X 10.11.6
 - Browser: Chrome
 - Node Version: 8.5.0
 - Vapid Version: ^0.3.0

**Comment by srobbin** [comment]
@vascogaspar Thanks for reaching out, and sorry to hear about the troubles. I'm going to close this issue, and [open it on the Vapid forums](https://forums.vapid.com/t/unable-to-apply-css-or-load-js-files-when-deploying-to-vapid/128) instead. We've been trying to use the forums for usage/hosting discussions, so we can keep GitHub focused on the CLI development. Talk to you on the forums in a bit...
