### ISSUE TITLE
Error on deploying website

### ISSUE THREAD

**Issue by Jack89ita** [vapid/vapid#95]
When deploying for the first time i get this:
![cattura](https://user-images.githubusercontent.com/15101779/48363825-220cef00-e6a7-11e8-9d0f-0a27d15368ee.PNG)
Any clue?

**Comment by Jack89ita** [comment]
Anyone? Please i cannot deploy my site...

**Comment by Jack89ita** [comment]
Made it work thanks to [this](https://stackoverflow.com/questions/6031214/git-how-to-use-netrc-file-on-windows-to-save-user-and-password)!

**Comment by srobbin** [comment]
@Jack89ita Sorry, I missed this. I'm glad you were able to find a fix, and appreciate you sharing it with us.
