### ISSUE TITLE
Upload image in WYSIWYG

### ISSUE THREAD

**Issue by walidvb** [vapid/vapid#96]
Can we consider uploading images in the WYSIWYG? Very handy when you want to allow users to post article-like content.
Currently users need technical knowledge to use the workaround described below.

**Describe the solution you'd like**
Add an image button to the wysiwyg.

**Describe alternatives you've considered**
Adding the images to an external service, using markdown and writing html code.

**Additional context**
I saw that quill has an `image` option, any reason not to enable it? It translates the image to base64, which prevents the need from adding an endpoint to handle the file upload.
If base64 is an issue, there seems to be an issue describing the file upload in [quill's repo](https://github.com/quilljs/quill/issues/1089)

**Comment by walidvb** [comment]
I hear you. In the case of quill, the image is inserted as base64, so I guess this would need to be handled browser-side(should we use base64).

I took a look into the source code of quill, though, and couldn't find anything related to that bit(nor was I able to plug into the quill image handler) 🤔. Upcoming version 2.x might solve this.

**Comment by srobbin** [comment]
I dig how they use base64—makes everything else downstream so much easier. I'll look into our options too.

**Comment by mk0r** [comment]
Just want to add my vote -- I imagine this is a dealbreaker for many people. Maybe cloudinary.com or imgix.com are worth looking into

**Comment by inmen** [comment]
<script>

var toolbarOptions = [
  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
  ['blockquote', 'code-block'],
  ['link', 'image', 'video'],
  [{ 'header': 1 }, { 'header': 2 }],               // custom button values
  [{ 'list': 'ordered'}, { 'list': 'bullet' }],
  [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
  [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
  [{ 'direction': 'rtl' }],                         // text direction

  [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
  [{ 'font': [] }],
  [{ 'align': [] }],

  ['clean']                                         // remove formatting button
];
var quill = new Quill('#editor-container', {
    modules: {
      toolbar: toolbarOptions
    },
    placeholder: 'Compose an epic...',
    theme: 'snow'
  });

var form = document.querySelector('form');
form.onsubmit = function() {
  // Populate hidden form on submit
  var body = document.querySelector('input[name=body]');
  body.value = JSON.stringify(quill.getContents());
  form.submit();
};

var IMGUR_API_URL = '{{ url("file/uploadfile") }}';
var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
{{-- var IMGUR_CLIENT_ID = 'bcab3ce060640ba';

function imageHandler(image, callback) {
  var data = new FormData();
  data.append('image', image);

  var xhr = new XMLHttpRequest();
  xhr.open('POST', IMGUR_API_URL, true);
  xhr.setRequestHeader('Authorization', 'Client-ID ' + IMGUR_CLIENT_ID);
  xhr.onreadystatechange = function() {
    if (xhr.readyState === 4) {
      var response = JSON.parse(xhr.responseText);
      if (response.status === 200 && response.success) {
        callback(response.data.link);
      } else {
        var reader = new FileReader();
        reader.onload = function(e) {
          callback(e.target.result);
        };
        reader.readAsDataURL(image);
      }
    }
  }
  xhr.send(data);
} --}}

function selectLocalImage() {
    const input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.click();

    // Listen upload local image and save to server
    input.onchange = () => {
      const file = input.files[0];

      // file type is only image.
      if (/^image\//.test(file.type)) {
        saveToServer(file);
      } else {
        alert('You could only fuck images.');
      }
    };
  }


  function OnProgress(event, position, total, percentComplete){
    //Progress bar
    console.log(total);
    $('#pb').width(percentComplete + '%') //update progressbar percent complete
    $('#pt').html(percentComplete + '%'); //update status text
}
  /**
   * Step2. save to server
   *
   * @param {File} file
   */
  function saveToServer(file) {
    const fd = new FormData();
    fd.append('image', file);

    $.ajax({
      type: "POST",
      url: IMGUR_API_URL,
      // data: {_token: CSRF_TOKEN, file:fd},
      data: fd,
      headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
      processData: false,
      contentType: false,
      success: function (data) {
        const url = data['url'];
        insertToEditor(url);
      },
      //beforeSubmit: beforeSubmit,
      uploadProgress:OnProgress, 
  });
  }

  /**
   * Step3. insert image url to rich editor.
   *
   * @param {string} url
   */
  function insertToEditor(url) {
    // push image url to rich editor.
    const range = quill.getSelection();
    quill.insertEmbed(range.index, 'image', url);
  }

  
  quill.getModule('toolbar').addHandler('image', () => {
    selectLocalImage();
  });
</script>

记得加这个，我是菜鸟被坑了一下午
<meta name="csrf-token" content="{{ csrf_token() }}" />

controller as:
    public function uploadFile(Request $request) {
        $file = $request->file('image');
        $filename = $file->getClientOriginalName();
        return response()->json([
            'status' => 'success',
            'data-id' => '123456',
            'url'=> 'http://localhost/uploads/'.$filename,
            'msg' => 'fuck it'
        ], 200);
     }

dont forgot the fuck route

**Comment by inmen** [comment]
`<script>

var toolbarOptions = [
  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
  ['blockquote', 'code-block'],
  ['link', 'image', 'video'],
  [{ 'header': 1 }, { 'header': 2 }],               // custom button values
  [{ 'list': 'ordered'}, { 'list': 'bullet' }],
  [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
  [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
  [{ 'direction': 'rtl' }],                         // text direction

  [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
  [{ 'font': [] }],
  [{ 'align': [] }],

  ['clean']                                         // remove formatting button
];
var quill = new Quill('#editor-container', {
    modules: {
      toolbar: toolbarOptions
    },
    placeholder: 'Compose an epic...',
    theme: 'snow'
  });

var form = document.querySelector('form');
form.onsubmit = function() {
  // Populate hidden form on submit
  var body = document.querySelector('input[name=body]');
  body.value = JSON.stringify(quill.getContents());
  form.submit();
};

var IMGUR_API_URL = '{{ url("file/uploadfile") }}';
var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

function selectLocalImage() {
    const input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.click();

    // Listen upload local image and save to server
    input.onchange = () => {
      const file = input.files[0];

      // file type is only image.
      if (/^image\//.test(file.type)) {
        saveToServer(file);
      } else {
        alert('You could only fuck images.');
      }
    };
  }


  function OnProgress(event, position, total, percentComplete){
    //Progress bar
    console.log(total);
    $('#pb').width(percentComplete + '%') //update progressbar percent complete
    $('#pt').html(percentComplete + '%'); //update status text
}
  /**
   * Step2. save to server
   *
   * @param {File} file
   */
  function saveToServer(file) {
    const fd = new FormData();
    fd.append('image', file);

    {{-- const xhr = new XMLHttpRequest();
    xhr.open('POST', IMGUR_API_URL);
    xhr.onload = () => {
      if (xhr.status === 200) {
        // this is callback data: url
        const url = JSON.parse(xhr.responseText).data;
        insertToEditor(url);
      }
    };
    xhr.send(fd); --}}

    $.ajax({
      type: "POST",
      url: IMGUR_API_URL,
      // data: {_token: CSRF_TOKEN, file:fd},
      data: fd,
      headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
      processData: false,
      contentType: false,
      success: function (data) {
        const url = data['url'];
        insertToEditor(url);
      },
      //beforeSubmit: beforeSubmit,
      uploadProgress:OnProgress, 
  });
  }

  /**
   * Step3. insert image url to rich editor.
   *
   * @param {string} url
   */
  function insertToEditor(url) {
    // push image url to rich editor.
    const range = quill.getSelection();
    quill.insertEmbed(range.index, 'image', url);
  }

  
  quill.getModule('toolbar').addHandler('image', () => {
    selectLocalImage();
  });
</script>`
记得加这个
`<meta name="csrf-token" content="{{ csrf_token() }}" />`
然后是controller
`    public function uploadFile(Request $request) {
        $file = $request->file('image');
        // //Display File Name
        $filename = $file->getClientOriginalName();
        $destinationPath = 'uploads';
        $file->move($destinationPath,$filename);
        return response()->json([
            'status' => 'success',
            'data-id' => '123456',
            'url'=> 'http://localhost/uploads/'.$filename,
            'msg' => 'fuck it'
        ], 200);
    }`


别忘了routes/web.php

**Comment by inmen** [comment]
``    public function showUploadFile(Request $request) {
        $file = $request->file('image');
        // //Display File Name
        $filename = $file->getClientOriginalName();
        $destinationPath = 'uploads';
        $file->move($destinationPath,$filename);
        return response()->json([
            'status' => 'success',
            'data-id' => '123456',
            'url'=> 'http://localhost/uploads/'.$filename,
            'msg' => 'fuck it'
        ], 200);
    }

**Comment by inmen** [comment]
`    public function showUploadFile(Request $request) {
        $file = $request->file('image');
        // //Display File Name
        $filename = $file->getClientOriginalName();
        $destinationPath = 'uploads';
        $file->move($destinationPath,$filename);
        return response()->json([
            'status' => 'success',
            'data-id' => '123456',
            'url'=> 'http://localhost/uploads/'.$filename,
            'msg' => 'fuck it'
        ], 200);
    }`

**Comment by walidvb** [comment]
Wondering if there was any progress made on this front? what is the current state of dev and PR acceptance?

**Comment by srobbin** [comment]
@walidvb Thanks for the nudge on this. I just released v0.6.0 which includes the ability to embed images from the WYSIWYG. It's turned off by default, but you can enable it by passing an `images=true` option. e.g.,

```
{{body type=html images=true}}
```

**Comment by walidvb** [comment]
Superb, thanks!
I guess a next step will be to allow resizing of the images, to avoid base64 embedding 8MB images. :)

**Comment by srobbin** [comment]
Yeah, that's kind of why I disabled it by default. We can proceed with caution and see if resizing/limiting becomes an issue.
